apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.fullname }}-config"
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_DB: "{{ .Values.postgres.database }}"
