apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: {{ .Values.namespace }}
data:
  HTTP_ENV: "{{ .Values.http.env }}"
  HTTP_PORT: "{{ .Values.http.port }}"

  PSQL_HOST: {{ .Values.psql.host }}
  PSQL_PORT: {{ .Values.psql.port }}
  PSQL_DATABASE: {{ .Values.psql.database }}
  PSQL_SSLMODE: {{ .Values.psql.sslmode }}
