apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets" 
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  PSQL_USER: "{{ .Values.psql.user }}"
  PSQL_PASSWORD: "{{ .Values.psql.password }}"
