apiVersion: v1
kind: ConfigMap
metadata:
  name: cartapi-config
data:
  HTTP_ENV: "local"
  HTTP_PORT: "8080"

  PSQL_HOST: "cartAPIStorage"
  PSQL_PORT: "5432"
  PSQL_DATABASE: "cartapi"
  PSQL_SSLMODE: "disable"
