name: Deploy image to Docker hub

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  deploy-image-to-dh:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v2

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/cartapi_app:latest .

      - name: Push image to DockerHub
        run:
          docker push ${{secrets.DOCKERHUB_USERNAME}}/cartapi_app:latest